### ISSUE TITLE
Divisioni Lavori

### ISSUE THREAD

**Issue by Giuseppe-Lo-Re** [Giuseppe-lore/git-branch-merge#1]
Ciao ragazzi, 
come da call precedente, vi trascrivo la divisione dei compiti:
@LucioGhedo : HTML
@jacoposergio : CSS
@DavidePisani : PHP 
@azzurragraziano : JS

Grazie a tutti e buon lavoro!

**Comment by jacoposergio** [comment]
ok, aspetto che @LucioGhedo completi la struttura base dell'html e inizio

**Comment by DavidePisani** [comment]
@Giuseppe-lore Ciao Giuseppe ho finito di creare il databse

**Comment by LucioGhedo** [comment]
> ok, aspetto che @LucioGhedo completi la struttura base dell'html e inizio

@jacoposergio la struttura base html è pronta

**Comment by Giuseppe-Lo-Re** [comment]
> @Giuseppe-lore Ciao Giuseppe ho finito di creare il databse

Ciao @DavidePisani , ottimo lavoro. Mi risultano degli errori sulla sintassi, puoi fare un check? 
Grazie mille

**Comment by jacoposergio** [comment]
> > ok, aspetto che @LucioGhedo completi la struttura base dell'html e inizio
> 
> @jacoposergio la struttura base html è pronta

va bene, inizio subito

**Comment by DavidePisani** [comment]
@Giuseppe-lore correzzione sintassi fatta, ;=)

**Comment by Giuseppe-Lo-Re** [comment]
@DavidePisani perfetto! Puoi procedere col merge,
grazie

**Comment by Giuseppe-Lo-Re** [comment]
> > ok, aspetto che @LucioGhedo completi la struttura base dell'html e inizio
> 
> @jacoposergio la struttura base html è pronta

@LucioGhedo ho controllato, perfetto grazie. puoi procedere col merge. @jacoposergio successivamente puoi procedere col css

**Comment by DavidePisani** [comment]
@Giuseppe-lore ho finito anche la chimata api, appena mi dai il via faccio il marge

**Comment by Giuseppe-Lo-Re** [comment]
> @Giuseppe-lore ho finito anche la chiamata api, appena mi dai il via faccio il marge
@DavidePisani  perfetto, procedi pure, grazie
